services:
  backend:
    image: matanlahmi/fullstack-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    image: matanlahmi/fullstack-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
